# Numpy

In [1]:
import numpy as np

In [3]:
#Numpy Array
a = np.array([1, 2, 3, 4, 5])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
#2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
b.shape

(2, 3)

In [ ]:
#Dot product
print("Array b : \n", b)
print("Transpose of array b : \n",b.T)

np.dot(b, b.T)

Array b : 
 [[1 2 3]
 [4 5 6]]
Transpose of array b : 
 [[1 4]
 [2 5]
 [3 6]]


array([[14, 32],
       [32, 77]])

In [17]:
#Creating random arrays
matrix = np.random.randint(60,100,(5,5))
print("Random Matrix : \n", matrix)

#Finding the max and min values in the matrix
print("Max value in the matrix : ", np.max(matrix), " at position ", np.argmax(matrix))
print("Min value in the matrix : ", np.min(matrix) , " at position ", np.argmin(matrix))
print("Sum of all elements in the matrix : ", np.sum(matrix))
print("unique values in the matrix : ", np.unique(matrix))

Random Matrix : 
 [[69 63 87 83 69]
 [81 84 80 62 71]
 [73 73 90 71 60]
 [75 66 87 82 71]
 [85 89 99 96 90]]
Max value in the matrix :  99  at position  22
Min value in the matrix :  60  at position  14
Sum of all elements in the matrix :  1956
unique values in the matrix :  [60 62 63 66 69 71 73 75 80 81 82 83 84 85 87 89 90 96 99]


In [ ]:
#Finding unique values in an array with counts
a = np.array([1, 0, 10, 10, -8, 6, 6, 6, 6, 8, 4, 2, 3, 4, 5]) 
b = np.unique(a, return_counts=True)
print("Array b : ", b)

Array b :  (array([-8,  0,  1,  2,  3,  4,  5,  6,  8, 10]), array([1, 1, 1, 1, 1, 2, 1, 4, 1, 2]))


In [22]:
#Slicing an array
matrix[2:4, 1:3]  # Slicing rows 2 to 3 and columns 1 to 2

array([[73, 90],
       [66, 87]], dtype=int32)